### ISSUE TITLE
やること洗い出し

### ISSUE THREAD

**Issue by tokku5552** [klsh1tt/Favotify#1]
とりあえずこのissueで大まかに流れ決めてissue立てていくか

- [x] Projects作って管理できるようにする
- [ ] UIのデザイン
- [ ] Firestoreの設計
- [ ] Projectの土台作り（とはいえcreate-react-appしたら終わり？)

**Comment by tokku5552** [comment]
後なんかある？

**Comment by klsh1tt** [comment]
- [ ] 要件定義（仕様詰め）
