### ISSUE TITLE
UIデザインを行う

### ISSUE THREAD

**Issue by tokku5552** [klsh1tt/Favotify#2]
Figmaでざっくりワイヤーフレームを作成する
基本SPA　×　Material UIで作る
デザインは後から修正すればいいのでとりあえず画面遷移とかボタンとかが何が必要かが分かればよい

**Comment by tokku5552** [comment]
@klsh1tt 
手書きで書いてくれたやつここにあげといてほしい

**Comment by klsh1tt** [comment]
![image](https://user-images.githubusercontent.com/8418485/112415438-282b3400-8d67-11eb-8420-dfb19aefb3ea.png)
![image](https://user-images.githubusercontent.com/8418485/112415466-31b49c00-8d67-11eb-9ac5-0ed4a1e1e911.png)
